server:
  servlet:
    context-path: /adRecommend
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3636/ad_recommend?serverTimezone=UTC
      username: root
      password: root
  redis:
    host: 116.198.241.204
    port: 6379
    database: 0
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# mybatis 相关配置
mybatis:
  configuration-properties:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true
  mapper-locations: mapper/*.xml

BookHub:
  path: D:\BookHub\img\

# AI
yuapi:
  client:
    access-key: ha76uhffa12leo01fd6mzlwld4z5lf5a
    secret-key: adkwsg4i1geob1blihqd66dcm8ik174i